[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Nicholas L <nicholas-l@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.43.0"
itertools = "0.10.3"
nalgebra = "0.32.2"
nom = "7.1.3"
once_cell = "1.17.1"
rayon = "1.7.0"
regex = "1.8.2"
lazy_static = "1.4.0"
# slab = "0.4.3"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "benchmark"
harness = false
